INSERT INTO users (first_name, last_name, username, password, email, profile_pic) VALUES
('Naruto', 'Uzumaki', 'naruto', 'password', 'naruto.uzumaki@example.com', 'naruto_pfp.png'),
('Sakura', 'Haruno', 'sakura', 'password', 'sakura.haruno@example.com', 'sakura_pfp.png'),
('Luffy', 'Monkey', 'luffy', 'password', 'luffy.monkey@example.com', 'luffy_pfp.png'),
('Goku', 'Son', 'goku', 'password', 'goku.son@example.com', 'goku_pfp.png'),
('Edward', 'Elric', 'edward', 'password', 'edward.elric@example.com', 'ed_pfp.png'),
('Natsu', 'Dragneel', 'natsu', 'password', 'natsu.dragneel@example.com', 'natsu_pfp.png'),
('Light', 'Yagami', 'light', 'password', 'light.yagami@example.com', 'light_pfp.png'),
('Inu', 'Yasha', 'inuyasha', 'password', 'inuyasha@example.com', 'inuyasha_pfp.png'),
('Mikasa', 'Ackerman', 'mikasa', 'password', 'mikasa.ackerman@example.com', 'mikasa_pfp.png'),
('Zenitsu', 'Agatsuma', 'zenitsu', 'password', 'zenitsu.agatsuma@example.com', 'zenitsu_pfp.png'),
('Gojo', 'Satoru', 'gojo', 'password', 'gojo.satoru@example.com', 'gojo_pfp.png'),
('Tanjiro', 'Kamado', 'tanjiro', 'password', 'tanjiro.kamado@example.com', 'tanjiro_pfp.png'),
('Megumi', 'Fushiguro', 'megumi', 'password', 'megumi.fushiguro@example.com', 'megumi_pfp.png'),
('Reigen', 'Arataka', 'reigen', 'password', 'reigen.arataka@example.com', 'reigen_pfp.png');