INSERT INTO projects (name, description, owner_id, max_participants, cover_photo_path, github_repo, figma_link, trello_link) VALUES
('Konoha Village Chat', 'A real-time messaging application for members of Konoha Village to communicate and strategize.', 1, 10, '89476.png', 'https://github.com/example/konoha-village-chat', 'https://figma.com/example/konoha-village-chat', 'https://trello.com/example/konoha-village-chat'),
('Naruto Missions Tracker', 'A tool for tracking and managing missions assigned to ninja teams, including mission status, rewards, and team assignments.', 2, 6, '1048204.png', 'https://github.com/example/naruto-missions-tracker', 'https://figma.com/example/naruto-missions-tracker', 'https://trello.com/example/naruto-missions-tracker'),
('Straw Hat Crew Task Manager', 'A project management tool for organizing and assigning tasks to the Straw Hat Crew.', 3, 9, '89476.png', 'https://github.com/example/crew-task-manager', 'https://figma.com/example/crew-task-manager', 'https://trello.com/example/crew-task-manager'),
('Dragon Ball Training Tracker', 'A project management tool for tracking and scheduling training sessions and battles.', 4, 5, '1048204.png', 'https://github.com/example/dragon-ball-training-tracker', 'https://figma.com/example/dragon-ball-training-tracker', 'https://trello.com/example/dragon-ball-training-tracker'),
('One Piece Treasure Market', 'An online platform for buying and selling treasure maps and pirate memorabilia.', 3, 8, '89476.png', 'https://github.com/example/one-piece-treasure-market', 'https://figma.com/example/one-piece-treasure-market', 'https://trello.com/example/one-piece-treasure-market'),
('Fullmetal Alchemist Research Hub', 'A networking site for alchemists and researchers to share discoveries and collaborate.', 5, 12, '1048204.png', 'https://github.com/example/fullmetal-alchemist-research-hub', 'https://figma.com/example/fullmetal-alchemist-research-hub', 'https://trello.com/example/fullmetal-alchemist-research-hub'),
('Fairy Tail Guild Manager', 'An app for managing guild members, missions, and magical training sessions.', 2, 6, '89476.png', 'https://github.com/example/fairy-tail-guild-manager', 'https://figma.com/example/fairy-tail-guild-manager', 'https://trello.com/example/fairy-tail-guild-manager'),
('Death Note Analysis Tool', 'An application for analyzing and tracking Death Notes to prevent misuse and identify patterns.', 7, 7, '1048204.png', 'https://github.com/example/death-note-analysis-tool', 'https://figma.com/example/death-note-analysis-tool', 'https://trello.com/example/death-note-analysis-tool'),
('Inuyasha Time Travel Diary', 'A tool for documenting and managing time travel experiences and encounters with historical figures.', 8, 6, '89476.png', 'https://github.com/example/inuyasha-time-travel-diary', 'https://figma.com/example/inuyasha-time-travel-diary', 'https://trello.com/example/inuyasha-time-travel-diary'),
('Attack on Titan Defense Simulator', 'A simulation game for strategizing and training in defense against Titans, based on "Attack on Titan."', 6, 10, '1048204.png', 'https://github.com/example/attack-on-titan-defense-simulator', 'https://figma.com/example/attack-on-titan-defense-simulator', 'https://trello.com/example/attack-on-titan-defense-simulator');