INSERT INTO projects (name, description, owner_id, max_participants, cover_photo_path, github_repo, figma_link, trello_link) VALUES
-- project 1
('Konoha Village Chat', 'A real-time messaging application for members of Konoha Village to communicate and strategize.', 1, 4, 'https://i.pinimg.com/originals/b1/71/ec/b171ec6c19523d1ee836cd2900af5893.jpg', 'https://github.com/example/konoha-village-chat', 'https://figma.com/example/konoha-village-chat', 'https://trello.com/example/konoha-village-chat'),
-- project 2
('Naruto Missions Tracker', 'A tool for tracking and managing missions assigned to ninja teams, including mission status, rewards, and team assignments.', 2, 4, 'https://i.pinimg.com/originals/ad/3d/ab/ad3dab47a175bf036e22a6e9545fa5e8.jpg', 'https://github.com/example/naruto-missions-tracker', 'https://figma.com/example/naruto-missions-tracker', 'https://trello.com/example/naruto-missions-tracker'),
-- project 3
('Straw Hat Crew Task Manager', 'A project management tool for organizing and assigning tasks to the Straw Hat Crew.', 3, 4, 'https://i.pinimg.com/originals/af/cc/de/afccdefeae5fee31e5dc4f56fe6b2bfe.jpg', 'https://github.com/example/crew-task-manager', 'https://figma.com/example/crew-task-manager', 'https://trello.com/example/crew-task-manager'),
-- project 4
('Dragon Ball Training Tracker', 'A project management tool for tracking and scheduling training sessions and battles.', 4, 4, 'https://qph.cf2.quoracdn.net/main-qimg-b54f828a154b86e5c4cbd8bffbf8fe93', 'https://github.com/example/dragon-ball-training-tracker', 'https://figma.com/example/dragon-ball-training-tracker', 'https://trello.com/example/dragon-ball-training-tracker'),
-- project 5
('One Piece Treasure Market', 'An online platform for buying and selling treasure maps and pirate memorabilia.', 3, 4, 'https://imgix.ranker.com/user_node_img/50135/1002685433/original/1002685433-photo-u-207946133', 'https://github.com/example/one-piece-treasure-market', 'https://figma.com/example/one-piece-treasure-market', 'https://trello.com/example/one-piece-treasure-market'),
-- project 6
('Fullmetal Alchemist Research Hub', 'A networking site for alchemists and researchers to share discoveries and collaborate.', 5, 4, 'https://i.pinimg.com/originals/5b/3f/46/5b3f46519bd873bc20e765ae122ed329.jpg', 'https://github.com/example/fullmetal-alchemist-research-hub', 'https://figma.com/example/fullmetal-alchemist-research-hub', 'https://trello.com/example/fullmetal-alchemist-research-hub'),
-- project 7
('Fairy Tail Guild Manager', 'An app for managing guild members, missions, and magical training sessions.', 6, 4, 'https://i.pinimg.com/originals/6f/2a/0a/6f2a0aa595ead6fab63424c6cd392635.jpg', 'https://github.com/example/fairy-tail-guild-manager', 'https://figma.com/example/fairy-tail-guild-manager', 'https://trello.com/example/fairy-tail-guild-manager'),
-- project 8
('Death Note Analysis Tool', 'An application for analyzing and tracking Death Notes to prevent misuse and identify patterns.', 7, 4, 'https://i.redd.it/7n2k6cqfeu381.jpg', 'https://github.com/example/death-note-analysis-tool', 'https://figma.com/example/death-note-analysis-tool', 'https://trello.com/example/death-note-analysis-tool'),
-- project 9
('Inuyasha Time Travel Diary', 'A tool for documenting and managing time travel experiences and encounters with historical figures.', 8, 4, 'https://m.media-amazon.com/images/M/MV5BMGI2MDI1N2MtMjkzNC00NjkwLWIyNjAtYWM0OTAyMjAwMjY2XkEyXkFqcGdeQXVyOTc5MDI5NjE@._V1_.jpg', 'https://github.com/example/inuyasha-time-travel-diary', 'https://figma.com/example/inuyasha-time-travel-diary', 'https://trello.com/example/inuyasha-time-travel-diary'),
-- project 10
('Attack on Titan Defense Simulator', 'A simulation game for strategizing and training in defense against Titans."', 9, 4, 'https://i.pinimg.com/originals/74/b2/c2/74b2c27db97a1c64a6b2fc77d34cc73f.jpg', 'https://github.com/example/attack-on-titan-defense-simulator', 'https://figma.com/example/attack-on-titan-defense-simulator', 'https://trello.com/example/attack-on-titan-defense-simulator'),
-- project 11
('Dragon Ball Tournament Organizer', 'An application for organizing and managing Dragon Ball tournaments, including schedules, participant tracking, and match results.', 4, 4, 'https://i.pinimg.com/originals/80/3d/bf/803dbf1f6f9c8e18fd297c29995d13dc.jpg', 'https://github.com/example/dragon-ball-tournament-organizer', 'https://figma.com/example/dragon-ball-tournament-organizer', 'https://trello.com/example/dragon-ball-tournament-organizer'),
-- project 12
('Saiyan Training Log', 'A tool for Saiyan warriors to log their training progress, battle encounters, and power level improvements.', 4, 4, 'https://i.pinimg.com/originals/04/77/90/04779067a514363b57857c1fbf898029.jpg', 'https://github.com/example/saiyan-training-log', 'https://figma.com/example/saiyan-training-log', 'https://trello.com/example/saiyan-training-log'),
-- project 13
('Thunder Breathing Training Hub', 'A platform for Demon Slayers to master Thunder Breathing techniques, track their training progress, and share their achievements. Includes resources, training modules, and performance tracking.', 10, 4, 'https://i.pinimg.com/originals/42/97/2e/42972e03f3ee6080e4d40e1d108e0dfc.jpg', 'https://github.com/example/zenitsu-thunder-breathing-training-hub', 'https://figma.com/example/zenitsu-thunder-breathing-training-hub', 'https://trello.com/example/zenitsu-thunder-breathing-training-hub'),
-- project 14
('Saiyan Battle Simulator', 'A simulation tool for Saiyan warriors to strategize and prepare for battles.', 4, 4, 'https://i.pinimg.com/originals/4d/f1/a0/4df1a066cbb26470ef104572a0c68e8d.jpg', 'https://github.com/example/saiyan-battle-simulator', 'https://figma.com/example/saiyan-battle-simulator', 'https://trello.com/example/saiyan-battle-simulator');