INSERT INTO chat_rooms (project_id) VALUES
(1), -- 'Konoha Village Chat'
(2), -- 'Naruto Missions Tracker'
(3), -- 'Straw Hat Crew Task Manager'
(4), -- 'Dragon Ball Training Tracker'
(5), -- 'One Piece Treasure Market'
(6), -- 'Fullmetal Alchemist Research Hub'
(7), -- 'Fairy Tail Guild Manager'
(8), -- 'Death Note Analysis Tool'
(9), -- 'Inuyasha Time Travel Diary'
(10), -- 'Attack on Titan Defense Simulator'
(11), -- 'Dragon Ball Tournament Organizer'
(12), -- 'Saiyan Training Log'
(13), -- 'Thunder Breathing Training Hub'
(14); -- 'Saiyan Battle Simulator'