DROP TABLE IF EXISTS todo_lists CASCADE;

CREATE TABLE todo_lists (
  id SERIAL PRIMARY KEY,
  project_id INT REFERENCES projects(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);