DROP TABLE IF EXISTS todo_list CASCADE;

CREATE TABLE todo_list (
  id SERIAL PRIMARY KEY,
  project_id INT REFERENCES projects(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);