DROP TABLE IF EXISTS group_chat CASCADE;

CREATE TABLE group_chat (
  id SERIAL PRIMARY KEY,
  project_id INT REFERENCES projects(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);